// Central registry of every static LaTeX formula in the visualizer.
// Edit a formula here and it updates everywhere it is referenced, and on the
// /formulas catalog page. Dynamic formulas that interpolate runtime state stay
// inline in their page. Generated by the initial extraction; maintain by hand.

export const FORMULAS = {
  // — Softmax —
  softmax01: String.raw`p_i = \frac{e^{z_i - \max(z)}}{\sum_j e^{z_j - \max(z)}}`,
  // — One-Hot Truth —
  oneHot01: String.raw`y_i = \begin{cases} 1 & \text{if } i = \text{target} \\ 0 & \text{otherwise} \end{cases}`,
  // — Cross-Entropy Loss —
  crossEntropy01: String.raw`\mathcal{L} = -\log(p_{\text{target}} + 10^{-12})`,
  // — Bigram Backward —
  bigramBackward01: String.raw`\nabla_z \mathcal{L} = p - \text{onehot}(\text{target})`,
  // — SGD Step —
  sgdStep01: String.raw`w' = w - \frac{\eta}{N} \, g`,
  // — Token Embedding —
  tokenEmbed01: String.raw`x = E[\text{idx}]`,
  // — Position Embedding —
  positionEmbed01: String.raw`p = P[t]`,
  // — Combined Input —
  combinedInput01: String.raw`h = E[\text{idx}] + P[t]`,
  combinedInput02: String.raw`P[t]`,
  combinedInput03: String.raw`h = E[\text{idx}_t] + P[t]`,
  // — Lower-Tri Mask —
  lowerTriMask01: String.raw`M_{i,j} = \begin{cases} 1 & j \le i \\ 0 & \text{otherwise} \end{cases}`,
  // — Normalize Rows —
  normalizeRows01: String.raw`W_{i,j} = \frac{M_{i,j}}{\sum_j M_{i,j}}`,
  // — Unembed Head —
  unembedHead01: String.raw`\text{logits} = h W_{\text{head}} + b`,
  // — Attention Concepts —
  attnConcepts01: String.raw`M_{i,j} = \begin{cases} 1 & j \le i \\ 0 & j > i \end{cases}`,
  attnConcepts02: String.raw`W_{i,j} = \frac{M_{i,j}}{\sum_{k=0}^{T-1} M_{i,k}}`,
  attnConcepts03: String.raw`\text{logits} = h \cdot W_{\text{head}} + b \in \mathbb{R}^{V}`,
  attnConcepts04: String.raw`\text{logits}_v = h \cdot w_v + b_v = \sum_{k=0}^{d-1} h[k] \cdot W_{\text{head}}[k, v] + b_v`,
  attnConcepts05: String.raw`s'_j = \begin{cases} s_j & j \le t \\ -\infty & j > t \end{cases}`,
  attnConcepts06: String.raw`h'_t = \sum_{j=0}^{T-1} a_j \cdot h_j \quad \in \mathbb{R}^d`,
  attnConcepts07: String.raw`
\begin{aligned}
  h_i &= E[\text{idx}_i] + P[i] && \text{(per-position hidden, all i)} \\
  s_j &\in \mathbb{R} && \text{(hand-picked raw scores)} \\
  s'_j &= \begin{cases} s_j & j \le t \\ -\infty & j > t \end{cases} && \text{(causal mask)} \\
  a_j &= \frac{\exp(s'_j)}{\sum_k \exp(s'_k)} && \text{(softmax → weights)} \\
  h'_t &= \sum_j a_j \cdot h_j && \text{(weighted sum)}
\end{aligned}
`,
  attnConcepts08: String.raw`s_{t,j} = \frac{q_t \cdot k_j}{\sqrt{d_k}}, \quad q_t = h_t W_Q,\ k_j = h_j W_K`,
  // — Attention-Weighted Sum —
  attnWeightedSum01: String.raw`h'_t = \sum_{j=0}^{T-1} a_j \cdot h_j \qquad h'_t[d] = \sum_{j} a_j \, h_j[d]`,
  attnWeightedSum02: String.raw`c_j = a_j \cdot h_j \in \mathbb{R}^{d_{\text{model}}},\qquad h'_t = \sum_j c_j`,
  // — Stage 2c-i Flow —
  stage2ci01: String.raw`h'_t = \sum_{j \le t} a_j \cdot h_j,\ \ a = \mathrm{softmax}(\mathrm{mask}(s))`,
  stage2ci02: String.raw`h_i = E[\text{idx}_i] + P[i] \quad \text{for } i = 0,\ldots,T-1`,
  stage2ci03: String.raw`s_j \in \mathbb{R} \quad\text{(you pick)},\qquad s'_j = \begin{cases} s_j & j \le t \\ -\infty & j > t \end{cases}`,
  stage2ci04: String.raw`a_j = \frac{\exp(s'_j)}{\sum_{k=0}^{T-1} \exp(s'_k)},\qquad \sum_{j=0}^{T-1} a_j = 1`,
  stage2ci05: String.raw`h'_t = \sum_{j=0}^{T-1} a_j \cdot h_j \qquad \text{(equivalently, } h'_t[d] = \sum_j a_j \, h_j[d] \text{ for each dim } d\text{)}`,
  stage2ci06: String.raw`c_j = a_j \cdot h_j \in \mathbb{R}^{d_{\text{model}}}`,
  // — Stage 1 Quiz —
  stage1Quiz01: String.raw`V \times n_\text{embd}`,
  stage1Quiz02: String.raw`V \times V`,
  stage1Quiz03: String.raw`T \times V`,
  stage1Quiz04: String.raw`V`,
  stage1Quiz05: String.raw`T \times T`,
  stage1Quiz06: String.raw`P_{i,j} = c_{i,j} - \bar{c}_j`,
  stage1Quiz07: String.raw`P_{i,j} = \frac{c_{i,j}}{\sum_k c_{i,k}}`,
  stage1Quiz08: String.raw`P = \mathrm{softmax}_\text{col}(c)`,
  stage1Quiz09: String.raw`P_{i,j} = \frac{c_{i,j}}{T}`,
  stage1Quiz10: String.raw`P_{i,j} = \log c_{i,j}`,
  stage1Quiz11: String.raw`W \in \mathbb{R}^{V \times V}`,
  stage1Quiz12: String.raw`W \in \mathbb{R}^{V}`,
  stage1Quiz13: String.raw`W \in \mathbb{R}^{V \times n_\text{embd}}`,
  stage1Quiz14: String.raw`p = ?\,(W[\text{prev}])`,
  stage1Quiz15: String.raw`p = \frac{W[\text{prev}]}{\sum_j W[\text{prev}, j]}`,
  stage1Quiz16: String.raw`p = \mathrm{softmax}(W[\text{prev}])`,
  stage1Quiz17: String.raw`p = \sigma(W[\text{prev}])`,
  stage1Quiz18: String.raw`p = \arg\max_j W[\text{prev}, j]`,
  stage1Quiz19: String.raw`p = \tanh(W[\text{prev}])`,
  stage1Quiz20: String.raw`y_j = [j = \text{target}]`,
  stage1Quiz21: String.raw`\frac{\partial \mathcal{L}_\text{CE}}{\partial \ell_j} = p_j - y_j`,
  stage1Quiz22: String.raw`W[\text{prev}] \leftarrow W[\text{prev}] - \eta\,(p - y)`,
  stage1Quiz23: String.raw`I_V`,
  stage1Quiz24: String.raw`d_\text{TV}(p, q) = ?`,
  stage1Quiz25: String.raw`\sum_j |p_j - q_j|`,
  stage1Quiz26: String.raw`\tfrac{1}{2}\sum_j |p_j - q_j|`,
  stage1Quiz27: String.raw`\sqrt{\sum_j (p_j - q_j)^2}`,
  stage1Quiz28: String.raw`\sum_j p_j \log\!\frac{p_j}{q_j}`,
  stage1Quiz29: String.raw`\max_j |p_j - q_j|`,
  stage1Quiz30: String.raw`\tfrac{1}{V}\sum_j (p_j - y_j)^2`,
  stage1Quiz31: String.raw`\mathcal{L} = -\log p_\text{target}`,
  stage1Quiz32: String.raw`\mathcal{L} = \sum_j \ell_j`,
  stage1Quiz33: String.raw`\mathcal{L} = \sum_j |p_j - y_j|`,
  stage1Quiz34: String.raw`\mathcal{L} = \max_j \ell_j - \ell_\text{target}`,
  stage1Quiz35: String.raw`W \leftarrow W + \eta\,(p - y)`,
  stage1Quiz36: String.raw`W[\text{prev}] \leftarrow y`,
  stage1Quiz37: String.raw`W[\text{prev}] \leftarrow W[\text{prev}] \cdot (p - y)`,
  stage1Quiz38: String.raw`W[\text{prev}] \leftarrow W[\text{prev}] / (p - y)`,
  // — Stage 2a Quiz —
  stage2Quiz01: String.raw`h_i = E[\text{idx}]_i + P[t]_i`,
  stage2Quiz02: String.raw`V\,n + T_\text{max}\,n`,
  stage2Quiz03: String.raw`V\,n + n\,V`,
  stage2Quiz04: String.raw`V\,n + T_\text{max}\,n + n\,V + V`,
  stage2Quiz05: String.raw`V\,n\,T_\text{max}`,
  stage2Quiz06: String.raw`V + n + T_\text{max}`,
  stage2Quiz07: String.raw`\text{params} = V\,n + T_\text{max}\,n + n\,V + V`,
  stage2Quiz08: String.raw`M_{i,j} = [i = j]`,
  stage2Quiz09: String.raw`M_{i,j} = \begin{cases} 1/(i+1) & j \le i \\ 0 & \text{otherwise} \end{cases}`,
  stage2Quiz10: String.raw`M_{i,j} = \begin{cases} 1 & j \ge i \\ 0 & \text{otherwise} \end{cases}`,
  stage2Quiz11: String.raw`M_{i,j} \sim U[0, 1)`,
  stage2Quiz12: String.raw`W = \mathrm{softmax}_{\text{col}}(M)`,
  stage2Quiz13: String.raw`W = M / \max(M)`,
  stage2Quiz14: String.raw`W_{i,j} = \frac{M_{i,j}}{\sum_{k} M_{i,k}}`,
  stage2Quiz15: String.raw`W = M\,M^{\top}`,
  stage2Quiz16: String.raw`W \sim U[0,1)^{T \times T}`,
  stage2Quiz17: String.raw`\sum_{j} W_{i,j} = 1 \quad \forall\,i`,
  stage2Quiz18: String.raw`H' = W \cdot H`,
  stage2Quiz19: String.raw`H'_t = \frac{1}{t+1} \sum_{j=0}^{t} H_j`,
  stage2Quiz20: String.raw`H'_0 \stackrel{?}{=} H_0`,
  stage2Quiz21: String.raw`W_{0} = [1, 0, 0, \dots]\ \Rightarrow\ H'_0 = 1 \cdot H_0`,
  stage2Quiz22: String.raw`W_\text{head} = 0`,
  stage2Quiz23: String.raw`W_\text{head} = E^{\top}`,
  stage2Quiz24: String.raw`W_\text{head} = P^{\top}`,
  stage2Quiz25: String.raw`\text{logits}[t, v] = H'_t \cdot E_v`,
  stage2Quiz26: String.raw`\text{logits} = H' \cdot E^{\top}`,
  stage2Quiz27: String.raw`\text{logits}[t, v] = H'_t \cdot E_v = \sum_{i} H'_{t, i} \, E_{v, i}`,
  stage2Quiz28: String.raw`-\sum_i H'_{t,i} \log E_{v,i}`,
  stage2Quiz29: String.raw`\cos\bigl(\angle(H_t, P_t)\bigr)`,
  stage2Quiz30: String.raw`p_v = \frac{\exp(\ell_v - m)}{\sum_k \exp(\ell_k - m)}, \quad m = \max_k \ell_k`,
  stage2Quiz31: String.raw`\ell_v - m \le 0 \ \Rightarrow\ \exp(\ell_v - m) \le 1`,
  stage2Quiz32: String.raw`|M| = T^2 = (10^6)^2 = 10^{12}`,
  stage2Quiz33: String.raw`|M| = V^2`,
  stage2Quiz34: String.raw`P_{t, 2k} = \sin\!\left(\tfrac{t}{10000^{2k/d}}\right),\ \ P_{t, 2k+1} = \cos\!\left(\tfrac{t}{10000^{2k/d}}\right)`,
  stage2Quiz35: String.raw`h'_t = \sum_{j \le t} a_j \, h_j,\ \ a = \mathrm{softmax}(\text{scores})`,
} as const;

export type FormulaKey = keyof typeof FORMULAS;

export const FORMULA_SECTIONS: { title: string; keys: FormulaKey[] }[] = [
  { title: "Softmax", keys: ['softmax01'] },
  { title: "One-Hot Truth", keys: ['oneHot01'] },
  { title: "Cross-Entropy Loss", keys: ['crossEntropy01'] },
  { title: "Bigram Backward", keys: ['bigramBackward01'] },
  { title: "SGD Step", keys: ['sgdStep01'] },
  { title: "Token Embedding", keys: ['tokenEmbed01'] },
  { title: "Position Embedding", keys: ['positionEmbed01'] },
  { title: "Combined Input", keys: ['combinedInput01', 'combinedInput02', 'combinedInput03'] },
  { title: "Lower-Tri Mask", keys: ['lowerTriMask01'] },
  { title: "Normalize Rows", keys: ['normalizeRows01'] },
  { title: "Unembed Head", keys: ['unembedHead01'] },
  { title: "Attention Concepts", keys: ['attnConcepts01', 'attnConcepts02', 'attnConcepts03', 'attnConcepts04', 'attnConcepts05', 'attnConcepts06', 'attnConcepts07', 'attnConcepts08'] },
  { title: "Attention-Weighted Sum", keys: ['attnWeightedSum01', 'attnWeightedSum02'] },
  { title: "Stage 2c-i Flow", keys: ['stage2ci01', 'stage2ci02', 'stage2ci03', 'stage2ci04', 'stage2ci05', 'stage2ci06'] },
  { title: "Stage 1 Quiz", keys: ['stage1Quiz01', 'stage1Quiz02', 'stage1Quiz03', 'stage1Quiz04', 'stage1Quiz05', 'stage1Quiz06', 'stage1Quiz07', 'stage1Quiz08', 'stage1Quiz09', 'stage1Quiz10', 'stage1Quiz11', 'stage1Quiz12', 'stage1Quiz13', 'stage1Quiz14', 'stage1Quiz15', 'stage1Quiz16', 'stage1Quiz17', 'stage1Quiz18', 'stage1Quiz19', 'stage1Quiz20', 'stage1Quiz21', 'stage1Quiz22', 'stage1Quiz23', 'stage1Quiz24', 'stage1Quiz25', 'stage1Quiz26', 'stage1Quiz27', 'stage1Quiz28', 'stage1Quiz29', 'stage1Quiz30', 'stage1Quiz31', 'stage1Quiz32', 'stage1Quiz33', 'stage1Quiz34', 'stage1Quiz35', 'stage1Quiz36', 'stage1Quiz37', 'stage1Quiz38'] },
  { title: "Stage 2a Quiz", keys: ['stage2Quiz01', 'stage2Quiz02', 'stage2Quiz03', 'stage2Quiz04', 'stage2Quiz05', 'stage2Quiz06', 'stage2Quiz07', 'stage2Quiz08', 'stage2Quiz09', 'stage2Quiz10', 'stage2Quiz11', 'stage2Quiz12', 'stage2Quiz13', 'stage2Quiz14', 'stage2Quiz15', 'stage2Quiz16', 'stage2Quiz17', 'stage2Quiz18', 'stage2Quiz19', 'stage2Quiz20', 'stage2Quiz21', 'stage2Quiz22', 'stage2Quiz23', 'stage2Quiz24', 'stage2Quiz25', 'stage2Quiz26', 'stage2Quiz27', 'stage2Quiz28', 'stage2Quiz29', 'stage2Quiz30', 'stage2Quiz31', 'stage2Quiz32', 'stage2Quiz33', 'stage2Quiz34', 'stage2Quiz35'] },
];
